
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabase as supabaseClient } from '@/lib/supabase';

// Re-export the supabase client from lib/supabase.ts to avoid duplication
export const supabase = supabaseClient;
